#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import MOSIM.mmi.math.ttypes
import MOSIM.mmi.core.ttypes
import MOSIM.mmi.scene.ttypes
import MOSIM.mmi.services.ttypes
import MOSIM.mmi.mmu.ttypes
import MOSIM.mmi.agent.ttypes
import MOSIM.mmi.avatar.ttypes
import MOSIM.mmi.constraints.ttypes
import MOSIM.mmi.cosim.ttypes
import MOSIM.mmi.register.ttypes

from thrift.transport import TTransport
all_structs = []
fix_spec(all_structs)
del all_structs
